name: FitDesk
targets:
  FitDesk:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Source
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.fitdesk.app
        CODE_SIGNING_ALLOWED: NO
